### PR TITLE
Remove Master students who left

### PR DESCRIPTION
**Pull request by nlessmann**
Master students are often not removed from the website when they leave DIAG, so once in a while I check based on the progress tickets and clean up.

@JasperLinmans @wouterbulten can you please confirm that Niels and Rens are indeed done with their internship at DIAG?

@thomasvdheuvel Martijn has already been removed from the website, if he's done could you please also close the ticket?

Thanks!

### CODE REVIEW

**Comment by JasperLinmans** [comment]
Niels is currently still working on his internship, he will be done at the end of February. Another master student of me: Gabriel Raya Rodríguez, however, is done. 

Do you want me to remove Gabriel's page from the content folder? And do that with Niels's page at the end of his internship as well?

**Comment by nlessmann** [comment]
Thanks, I've updated the pull request to remove Gabriel but leave Niels on "active". Would be great if you could remove him then when he's done.

**Comment by thomasvdheuvel** [comment]
@nlessmann Martijn is not done with his project, because he has submitted a journal paper which is still under review. I will close his ticket once this is completed.

**Comment by nlessmann** [comment]
@thomasvdheuvel okay, thanks!

Rens seems to be still active, so removing only Gabriel.

**Pull request merged**
