### PR TITLE
Improve layout for tables in .page-content

### PR DESCRIPTION
**Pull request by pkcakeout**
Improve layout of dense, hard-to-read tables in current layout for content pages. Currently, tables look like this:

image

After merging the same table would look like this:

image

Reference link: https://rse.diagnijmegen.nl/projects/diag-sol/

Note: *I did not test my modifications and am not sure if they will work.*

### CODE REVIEW

**Comment by wouterbulten** [comment]
I agree, tables should have a better default layout. Problem is that the bootstrap classes are not automatically applied which results in the layout you mention. Simply adding the classes gives a better result already:

image

Instead of adding more css I would opt for automatically adding the correct classes to generated content. We can use something like https://github.com/ingwinlu/pelican-bootstrapify for this.

**Comment by pkcakeout** [comment]
Hi Wouter!

Thanks for the quick response. I understand the issue why the tables are so weird now - I thought it was simply an oversight. Is it possible to have something like my proposed solution as a stand-in though until you/someone has time to fix this properly then (or can I somehow add the classes manually to my document? I guess not?)

If you think that this is not an option, I will include a screenshot of a table instead of an actual table for now as a workaround. The particular linked page should be "done" and readable this week because we want to use it as reference material for a job opening that is going public this week.

**Comment by wouterbulten** [comment]
Good to that you mention it. I will make something today.

**Comment by wouterbulten** [comment]
@pkcakeout done! Let me know if this is good enough for now. (Could still use some tweaking but that's for a later date)

**Comment by pkcakeout** [comment]
Let's continue the discussion on the actual ticket!

**Pull request closed without merging**
